#访问一个网站时，默认是80端口，给用户80端口，用户就可以不用加端口直接访问页面
server:
    port: 80

spring:
    application:
        #微服务名称
        name: cloud-order-service

#eureka服务注册中心
eureka:
    client:
        #true表示向注册中心注册自己，默认为true
        register-with-eureka: true
        #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
        fetch-registry: true
        service-url:
            #defaultZone: http://localhost:7001/eureka
            #集群版
            defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

    instance:
        instance-id: consumer80    #修改显示的主机名
        prefer-ip-address: true   #访问路径可以显示ip地址