server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE # lb 为负载均衡
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
        # 上面表示 如果要访问http://localhost:8001/get/payment/** 需要
        # http://localhost:9527/get/payment/**

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE # lb 为负载均衡
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
          #- After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
          #- Cookie=username,zhangshuai #并且Cookie是username=zhangshuai才能访问
          #- Header=X-Request-Id, \d+ #请求头中要有X-Request-Id属性并且值为整数的正则表达式
          #- Host=**.atguigu.com
          #- Method=GET
          #- Query=username, \d+ #要有参数名称并且是正整数才能路由

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka