###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
####consul注册中心地址
  cloud:
    consul:
      host: 192.168.23.134
      port: 8500
      discovery:
        hostname: 192.168.10.7
        service-name: ${spring.applicat ion.name}